### ISSUE TITLE
Crash when creating a geometry node

### ISSUE THREAD

**Issue by tkarabela** [eliemichel/OpenMfxForBlender#81]
I've encountered a crash when adding OpenMfx geometry node, following instructions from https://openmesheffect.org/QuickStart/using-openmfx.html#as-a-geometry-node

**Steps to reproduce**
- Run Blender
- Switch to Geometry Nodes tab
- Add Geometry Nodes
- Add Mesh Primitives > OpenMfx Plugin node
- SIGSEGV

**My setup**
The crash happens with `mfx-v0.16.0-rc1` (`d8592ce049a4a7dfae40335fdad430ce6679b588`) which I've built on Ubuntu 20.04, x86-64 in Debug configuration.

**The crash**
It happens in `MFX_node_get_effect_count`, where `m_library` is NULL inside the `runtime` struct. I'm not familiar with the geometry nodes part of the mfx host so unfortunately don't know where to look further.

![Screenshot from 2022-11-11 23-58-39](https://user-images.githubusercontent.com/8166544/201443882-7a95a02e-c4c6-42d2-b46b-48a5bbc2473f.png)

**Notes**
- Using OpenMfx as a modifier works fine, I've tested it with https://github.com/eliemichel/MfxExamples
- It doesn't matter if I try to add OpenMfx geometry node right away or if I first apply an OpenMfx modifier, load MfxExamples `.ofx`, select an effect (which works as expected), and after that try to add the geometry node

P.S. Nice to see OpenMfx moving forward @eliemichel! :)

**Comment by eliemichel** [comment]
My bad, I was a bit too in a hurry in my last update! To be fixed in a minute.

Nice to see you around :) I started recently to read over all our discussions to log the important ideas here https://openmfx.org/Rfc/002-edge-representation.html ! An OpenMfx keeps on living, especially thanks to @YassineMankai who I could hire for an internship with the Epic MegaGrant. What have you been working on lately?

**Comment by tkarabela** [comment]
Thanks for the fix! I've just sent you an e-mail :)
